export interface CountryDialCode {
  name: string;
  code: string;
  dialCode: string;
}

export const countryDialCodes: CountryDialCode[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Argentina", code: "AR", dialCode: "+54" },
  { name: "Armenia", code: "AM", dialCode: "+374" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "Austria", code: "AT", dialCode: "+43" },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994" },
  { name: "Belgium", code: "BE", dialCode: "+32" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Belarus", code: "BY", dialCode: "+375" },
  { name: "Brazil", code: "BR", dialCode: "+55" },
  { name: "Canada", code: "CA", dialCode: "+2" },
  { name: "Switzerland", code: "CH", dialCode: "+41" },
  { name: "Chile", code: "CL", dialCode: "+56" },
  { name: "China", code: "CN", dialCode: "+86" },
  { name: "Colombia", code: "CO", dialCode: "+57" },
  { name: "Czechia", code: "CZ", dialCode: "+420" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "Denmark", code: "DK", dialCode: "+45" },
  { name: "Algeria", code: "DZ", dialCode: "+213" },
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "Spain", code: "ES", dialCode: "+34" },
  { name: "Ethiopia", code: "ET", dialCode: "+251" },
  { name: "Finland", code: "FI", dialCode: "+358" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "Greece", code: "GR", dialCode: "+30" },
  { name: "Hong Kong", code: "HK", dialCode: "+852" },
  { name: "Hungary", code: "HU", dialCode: "+36" },
  { name: "Indonesia", code: "ID", dialCode: "+62" },
  { name: "Ireland", code: "IE", dialCode: "+353" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "Iraq", code: "IQ", dialCode: "+964" },
  { name: "Iran", code: "IR", dialCode: "+98" },
  { name: "Iceland", code: "IS", dialCode: "+354" },
  { name: "Italy", code: "IT", dialCode: "+39" },
  { name: "Japan", code: "JP", dialCode: "+81" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "South Korea", code: "KR", dialCode: "+82" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+07" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94" },
  { name: "Lithuania", code: "LT", dialCode: "+370" },
  { name: "Luxembourg", code: "LU", dialCode: "+352" },
  { name: "Latvia", code: "LV", dialCode: "+371" },
  { name: "Morocco", code: "MA", dialCode: "+212" },
  { name: "Myanmar", code: "MM", dialCode: "+95" },
  { name: "Mexico", code: "MX", dialCode: "+52" },
  { name: "Malaysia", code: "MY", dialCode: "+60" },
  { name: "Nigeria", code: "NG", dialCode: "+234" },
  { name: "Netherlands", code: "NL", dialCode: "+31" },
  { name: "Norway", code: "NO", dialCode: "+47" },
  { name: "Nepal", code: "NP", dialCode: "+977" },
  { name: "New Zealand", code: "NZ", dialCode: "+64" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Poland", code: "PL", dialCode: "+48" },
  { name: "Portugal", code: "PT", dialCode: "+351" },
  { name: "Palestine", code: "PS", dialCode: "+970" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Romania", code: "RO", dialCode: "+40" },
  { name: "Russia", code: "RU", dialCode: "+7" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
  { name: "Sweden", code: "SE", dialCode: "+46" },
  { name: "Singapore", code: "SG", dialCode: "+65" },
  { name: "Slovakia", code: "SK", dialCode: "+421" },
  { name: "Thailand", code: "TH", dialCode: "+66" },
  { name: "Turkey", code: "TR", dialCode: "+90" },
  { name: "Taiwan", code: "TW", dialCode: "+886" },
  { name: "Ukraine", code: "UA", dialCode: "+380" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998" },
  { name: "Venezuela", code: "VE", dialCode: "+58" },
  { name: "Vietnam", code: "VN", dialCode: "+84" },
  { name: "South Africa", code: "ZA", dialCode: "+27" },
];

export const statesByCountry: Record<string, string[]> = {
  // Existing countries
  BD: [
    "Dhaka",
    "Chittagong",
    "Rajshahi",
    "Khulna",
    "Barishal",
    "Sylhet",
    "Rangpur",
  ],
  PS: ["Gaza", "West Bank", "Jenin", "Nablus", "Hebron"],
  IR: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz"],
  US: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
  ],
  CA: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
  ],
  GB: ["England", "Scotland", "Wales", "Northern Ireland"],
  AU: [
    "New South Wales",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  IN: [
    "Andhra Pradesh",
    "Bihar",
    "Delhi",
    "Gujarat",
    "Karnataka",
    "Maharashtra",
    "Punjab",
    "Tamil Nadu",
    "Uttar Pradesh",
    "West Bengal",
  ],
  BR: [
    "Acre",
    "Bahia",
    "Ceará",
    "Minas Gerais",
    "Paraná",
    "Rio de Janeiro",
    "Rio Grande do Sul",
    "Santa Catarina",
    "São Paulo",
  ],
  DE: [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "North Rhine-Westphalia",
  ],
  FR: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Corsica",
    "Grand Est",
    "Île-de-France",
    "Normandy",
    "Occitanie",
    "Provence-Alpes-Côte d'Azur",
  ],
  JP: [
    "Hokkaido",
    "Tohoku",
    "Kanto",
    "Chubu",
    "Kansai",
    "Chugoku",
    "Shikoku",
    "Kyushu",
  ],
  MX: [
    "Aguascalientes",
    "Baja California",
    "Chiapas",
    "Jalisco",
    "Mexico City",
    "Nuevo León",
    "Quintana Roo",
    "Yucatán",
  ],
  ZA: [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
  ],
  NG: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
  ],
  PK: [
    "Balochistan",
    "Gilgit-Baltistan",
    "Islamabad",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
  ],
  RU: [
    "Altai Republic",
    "Bashkortostan",
    "Chechnya",
    "Dagestan",
    "Irkutsk Oblast",
    "Kaliningrad Oblast",
    "Moscow",
    "Saint Petersburg",
    "Tatarstan",
  ],
  TR: [
    "Adana",
    "Ankara",
    "Antalya",
    "Bursa",
    "Istanbul",
    "Izmir",
    "Konya",
    "Trabzon",
  ],
  CN: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Guangdong",
    "Hong Kong",
    "Shanghai",
    "Tianjin",
    "Xinjiang",
    "Zhejiang",
  ],
  SA: [
    "Al Bahah",
    "Al Jawf",
    "Eastern Province",
    "Ha'il",
    "Jizan",
    "Makkah",
    "Medina",
    "Riyadh",
    "Tabuk",
  ],
  EG: [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Cairo",
    "Dakahlia",
    "Giza",
    "Luxor",
    "Port Said",
    "Suez",
  ],
  IT: [
    "Abruzzo",
    "Aosta Valley",
    "Apulia",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Lazio",
    "Lombardy",
    "Sicily",
    "Tuscany",
  ],
  ES: [
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country",
    "Canary Islands",
    "Catalonia",
    "Galicia",
    "Madrid",
    "Valencia",
  ],
  KR: [
    "Busan",
    "Daegu",
    "Daejeon",
    "Gangwon",
    "Gwangju",
    "Gyeonggi",
    "Incheon",
    "Jeju",
    "Seoul",
    "Ulsan",
  ],
  ID: [
    "Aceh",
    "Bali",
    "Banten",
    "Jakarta",
    "East Java",
    "West Java",
    "Papua",
    "Riau",
    "South Sulawesi",
    "West Sumatra",
  ],
  PH: [
    "Bicol",
    "Cagayan Valley",
    "Calabarzon",
    "Central Luzon",
    "Central Visayas",
    "Ilocos",
    "Metro Manila",
    "Western Visayas",
    "Zamboanga Peninsula",
  ],
  VN: [
    "An Giang",
    "Bà Rịa-Vũng Tàu",
    "Đà Nẵng",
    "Hà Nội",
    "Hồ Chí Minh City",
    "Hải Phòng",
    "Khánh Hòa",
    "Lâm Đồng",
    "Quảng Ninh",
    "Thừa Thiên-Huế",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Chonburi",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Phuket",
    "Prachuap Khiri Khan",
    "Songkhla",
    "Surat Thani",
  ],
  MY: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Melaka",
    "Penang",
    "Perak",
    "Sabah",
    "Sarawak",
    "Selangor",
  ],
};
